name: Mingw-w64-x64

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  mingw:
    runs-on: ubuntu-20.04
    name: Mingw-w64-x64
    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update -y &&
        sudo apt-get install -y cmake mingw-w64

    - name: Generate CMake Projects
      working-directory: ${{runner.workspace}}
      run: cmake -S Tolk -B output -DCMAKE_INSTALL_PREFIX=install -DCMAKE_TOOLCHAIN_FILE=../CMake/mingwcc64.toolchain.cmake

    - name: Build CMake Projects
      working-directory: ${{runner.workspace}}
      run: cmake --build output

    - name: Install CMake Projects
      working-directory: ${{runner.workspace}}
      run: cmake --build output --target install

    - uses: actions/upload-artifact@v3
      with:
        name: tolk-binaries-mingw64-x64
        path: ${{runner.workspace}}/install
